version: '3.9'

services:

# ╭──────────────────────────────────────────────────────────╮
# │                   NGINX PROXY MANAGER                    │
# ╰──────────────────────────────────────────────────────────╯
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    env_file: .env
    environment:
      DB_MYSQL_HOST: "nginx_proxy_manager_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: $PROXY_MANAGER_MYSQL_USER
      DB_MYSQL_PASSWORD: $PROXY_MANAGER_MYSQL_PASSWORD
      DB_MYSQL_NAME: $PROXY_MANAGER_MYSQL_DATABASE
    volumes:
      - ./data/app:/data
      - ./data/letsencrypt:/etc/letsencrypt

  nginx_proxy_manager_db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $PROXY_MANAGER_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $PROXY_MANAGER_MYSQL_DATABASE
      MYSQL_USER: $PROXY_MANAGER_MYSQL_USER
      MYSQL_PASSWORD: $PROXY_MANAGER_MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql